sudo: false
language: node_js
cache:
  directories:
  - node_modules
notifications:
  email: false
node_js:
- 4
- iojs-v3
- iojs-v2
- iojs-v1
- '0.12'
- '0.10'
before_install:
- npm install -g npm@^2
before_script:
- npm prune
after_success:
- 'curl -Lo travis_after_all.py https://git.io/vLSON'
- python travis_after_all.py
- export $(cat .to_export_back)
- npm run semantic-release
branches:
  except:
  - /^v\d+\.\d+\.\d+$/
