name: semantic-release-plus

on:
  push:
    branches:
      - master
      - next
      - beta
      - alpha
      - '*.x' # maintenance releases branches
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  lint_workspace:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          cache: npm
      - run: npm ci
      - run: npx nx workspace-lint
  lint_test_build:
    needs: lint_workspace
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: 
          - name: lint 
          - name: test 
            args: --code-coverage 
          - name: build
            args: --configuration=production
            output:
              name: packages
              path: dist/packages
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          cache: npm
      - run: npm ci
      - name: Build affected
        uses: mansagroup/nrwl-nx-action@v2.0.6
        with:
          targets: ${{ matrix.target.name }}
          args: ${{ matrix.target.args }}
          nxCloud: 'true'
        env:
          NX_CLOUD_ACCESS_TOKEN: ${{secrets.NX_CLOUD_ACCESS_TOKEN}}
      - name: Save build output
        if: ${{ matrix.target.output.name !== "" }}
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.target.output.name }}
          path: ${{ matrix.target.output.path }}

  release:
    needs:
      - lint_test_build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          cache: npm
      - run: npm ci
      - name: Get build output
        continue-on-error: true
        uses: actions/download-artifact@v2
        with:
          name: packages
          path: dist/packages
      - name: Release affected
        uses: mansagroup/nrwl-nx-action@v2.0.6
        with:
          targets: release
          nxCloud: 'true'
        env:
          NX_CLOUD_ACCESS_TOKEN: ${{secrets.NX_CLOUD_ACCESS_TOKEN}}
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_BOT_GITHUB_PAT }}
          NPM_TOKEN: ${{ secrets.SEMANTIC_RELEASE_BOT_NPM_TOKEN }}

  # build:

  #   runs-on: ubuntu-latest

  #   strategy:
  #     matrix:
  #       node-version: [12.x, 14.x, 16.x]
  #       # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Use Node.js ${{ matrix.node-version }}
  #     uses: actions/setup-node@v2
  #     with:
  #       node-version: ${{ matrix.node-version }}
  #       cache: 'npm'
  #   - run: npm ci
  #   - run: npm run build --if-present
  #   - run: npm test
