name: Release
on:
  push:
    branches:
      - master
      - next
      - beta
      - "*.x" # maintenance releases branches
  
  # run on pr also to validate correct PR behavior
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: npm
      # run npm link to install current directory globally this is similar to `npm install -g semantic-release`
      # we need to eat our own dogfood not our previous published version
      - run: npm link
      - run: npx semantic-release-plus
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.SEMANTIC_RELEASE_BOT_NPM_TOKEN }}
